config/routes.rb
Rails.application.routes.draw do
  # Home page
  root 'pages#home'
  
  # Search test page
  get 'search-test', to: 'pages#search_test'
  
  # Boards section
  get 'boards', to: 'boards#index'
  
  # Board category routes
  get 'boards/pixel-controllers', to: 'boards#pixel_controllers'
  get 'boards/relay-controllers', to: 'boards#relay_controllers'
  get 'boards/interactive-controllers', to: 'boards#interactive_controllers'
  get 'boards/portable-controllers', to: 'boards#portable_controllers'
  get 'boards/power-distribution', to: 'boards#power_distribution'
  get 'boards/dmx-controllers', to: 'boards#dmx_controllers'
  
  # Generic board routes - handles all board pages automatically
  get 'boards/:board', to: 'boards#show', as: :board
  get 'boards/:board/:page', to: 'boards#show', as: :board_page
  
  # About Baldrick section
  get 'about', to: 'about#index'
  
  # Baldrick Breakthroughs section
  get 'breakthroughs', to: 'breakthroughs#index'
  get 'breakthroughs/turnip-network', to: 'breakthroughs#turnip_network'
  get 'breakthroughs/kluster', to: 'breakthroughs#kluster'
  get 'breakthroughs/ce-ukca-certification', to: 'breakthroughs#ce_ukca_certification'
  get 'breakthroughs/turniput', to: 'breakthroughs#turniput'
  get 'breakthroughs/hodgical-test-mode', to: 'breakthroughs#hodgical_test_mode'
  get 'breakthroughs/cunningfx', to: 'breakthroughs#cunningfx'
  
  # FAQ section
get 'faq', to: 'faq#index'
  
  # Fun Stuff section
get 'fun-stuff', to: 'fun_stuff#index'
get 'fun-stuff/release-notes', to: 'fun_stuff#release_notes'
get 'fun-stuff/stls-and-mounts', to: 'fun_stuff#stls_and_mounts'
get 'fun-stuff/board-dimensions', to: 'fun_stuff#board_dimensions'
get 'fun-stuff/faq', to: 'fun_stuff#faq'
get 'fun-stuff/problem-solver', to: 'fun_stuff#problem_solver'
get 'fun-stuff/panic-mode', to: 'fun_stuff#panic_mode'
get 'fun-stuff/customer-showcase', to: 'fun_stuff#customer_showcase'
  
  # Where to buy page
  get 'where-to-buy-baldrick-boards', to: 'pages#where_to_buy'
  
  # Support section
  get 'support', to: 'support#index'
  get 'support/software', to: 'support#software'
  get 'support/asking-for-help', to: 'support#asking_for_help'
  
  # Catch all unmatched routes and show 404
  match '*path', to: 'application#not_found', via: :all
end

app/views/shared/_breadcrumbs.html.slim
/ Breadcrumb Navigation
nav.text-sm.text-gray-500.mb-6
  .flex.items-center.space-x-2
    - breadcrumbs.each_with_index do |crumb, index|
      - if index > 0
        svg.h-4.w-4.text-gray-400 fill="currentColor" viewBox="0 0 20 20"
          path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"
      
      - if crumb[:path].present?
        a.hover:text-gray-700.transition-colors href=crumb[:path] = crumb[:title]
      - else
        span.text-gray-900.font-medium = crumb[:title]

app/views/shared/_footer.html.slim
/ Footer
footer.bg-purple-900.text-white
  .max-w-6xl.mx-auto.px-4.sm:px-6.lg:px-8.py-12
    .grid.md:grid-cols-3.gap-8
      / Column 1: Our Boards
      div
        h3.text-lg.font-semibold.mb-4 Our Boards
        ul.space-y-2.text-purple-200
          li
            = link_to "Baldrick8 Docs", board_path("baldrick8"), class: "hover:text-white transition-colors"
          li
            = link_to "Baldrick17 Docs", board_path("baldrick17"), class: "hover:text-white transition-colors"
          li
            = link_to "BaldrickSwitchy Docs", board_path("baldrickswitchy"), class: "hover:text-white transition-colors"
          li
            = link_to "BaldrickDMX Docs", board_path("baldrickdmx"), class: "hover:text-white transition-colors"
          li
            = link_to "BaldrickInput1 Docs", board_path("baldrickinput1"), class: "hover:text-white transition-colors"
          li
            = link_to "BaldrickSignals Docs", board_path("baldricksignals"), class: "hover:text-white transition-colors"
      
      / Column 2: Help
      div
        h3.text-lg.font-semibold.mb-4 Help
        ul.space-y-2.text-purple-200
          li
            = link_to "Baldrick Boards Facebook Group", "https://www.facebook.com/groups/baldrickboards", target: "_blank", class: "hover:text-white transition-colors"
          li
            = link_to "Hardware Support Form", support_path, class: "hover:text-white transition-colors"
          li
            = link_to "Fun Stuff", fun_stuff_path, class: "hover:text-white transition-colors"
          li
            = link_to "FAQ", faq_path, class: "hover:text-white transition-colors"
      
      / Column 3: More
      div
        h3.text-lg.font-semibold.mb-4 More
        ul.space-y-2.text-purple-200
          li
            = link_to "About Baldrick", about_path, class: "hover:text-white transition-colors"
          li
            = link_to "Where to Buy", where_to_buy_baldrick_boards_path, class: "hover:text-white transition-colors"
          li
            = link_to "Complaints", "https://www.youtube.com/watch?v=g4IQjUpTNVU", target: "_blank", class: "hover:text-white transition-colors"
        
        / Seasonal Themes Dropdown
        .mt-6
          h4.text-sm.font-semibold.mb-2.text-purple-200 Seasonal Themes
          .relative
            select.bg-purple-800.text-white.border.border-purple-600.rounded-md.px-3.py-2.text-sm.w-full.focus:outline-none.focus:ring-2.focus:ring-purple-500.focus:border-transparent data-seasonal-themes-target="select" data-action="change->seasonal-themes#change"
              option value="default" Default Theme
              option value="christmas" Christmas
              option value="halloween" Halloween
              option value="easter" Easter
              option value="british" 4th July
  
  / Copyright
  .border-t.border-purple-800
    .max-w-6xl.mx-auto.px-4.sm:px-6.lg:px-8.py-6
      .text-center.text-purple-300
        p Copyright © 2025 www.ilightthat.com

app/views/shared/_page_header.html.slim
/ Page Header Component
.bg-gradient-to-r.from-indigo-600.to-purple-600.px-8.py-12.text-white.relative.overflow-hidden
  .max-w-4xl.mx-auto.relative.z-10
    h1.text-4xl.font-bold.mb-4 = local_assigns[:title]
    - if local_assigns[:subtitle].present?
      p.text-xl.text-indigo-100 = local_assigns[:subtitle]
  
  - if local_assigns[:image_url].present?
    / Overlapping Image
    .absolute.right-0.top-0.bottom-0.w-1/3.opacity-20
      = image_tag local_assigns[:image_url], alt: (local_assigns[:image_alt] || local_assigns[:title]), class: "w-full h-full object-cover"
  - elsif params[:controller] == 'boards' && params[:board].present?
    / Overlapping Image
    .absolute.right-0.top-0.bottom-0.w-1/3.opacity-20
      = image_tag "#{params[:board]}/board.png", alt: (local_assigns[:image_alt] || local_assigns[:title]), class: "w-full h-full object-cover"

app/views/shared/_search.html.slim
/ Search Component
div data-controller="search" class="relative"
  / Search Input
  .relative
    input[
      type="text"
      data-search-target="input"
      placeholder="Search boards, breakthroughs, FAQ... (⌘K)"
      class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors"
    ]
    / Search Icon
    .absolute.inset-y-0.left-0.pl-3.flex.items-center.pointer-events-none
      svg.h-5.w-5.text-gray-400 fill="currentColor" viewBox="0 0 20 20"
        path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"
  
  / Search Results Dropdown
  .absolute.z-50.w-full.mt-1.bg-white.border.border-gray-200.rounded-lg.shadow-lg.max-h-96.overflow-y-auto.hidden data-search-target="results"
    / Results will be populated by JavaScript